export type MenuItem={id:string;name:string;price:number;description:string;tag?:string};export type Restaurant={slug:string;name:string;category:string;rating:number;delivery:string;image:string;accent:string;description:string;items:MenuItem[]};
const item=(id:string,name:string,price:number,description:string,tag?:string):MenuItem=>({id,name,price,description,tag});
export const restaurants:Restaurant[]=[
{slug:'ahmed-biryani',name:'Ahmed Biryani',category:'Biryani',rating:4.7,delivery:'25–35 min',image:'/images/beef-biryani.jpg',accent:'Biryani',description:'Hyderabad-style rice, slow-cooked with fragrant spices.',items:[item('ab1','Beef Biryani',285,'Tender beef, basmati rice and aromatic masala','Best seller'),item('ab2','Chicken Biryani',140,'Single-serving chicken biryani'),item('ab3','Korma',350,'Creamy, slow-cooked curry with warm spices')]},
{slug:'kfc',name:'KFC Hyderabad',category:'Fried Chicken',rating:5,delivery:'30–40 min',image:'/images/chicken-biryani.jpg',accent:'Fried Chicken',description:'Crispy chicken, iconic burgers and shareable buckets.',items:[item('k1','Krunch Burger',310,'Crunchy chicken fillet with fresh lettuce'),item('k2','Mighty Zinger',770,'Spicy chicken, cheese and signature sauce','Popular'),item('k3','Hot Wings Bucket',670,'A bucket of fiery, crispy wings')]},
{slug:'dominos',name:"Domino's Pizza",category:'Pizza',rating:4.6,delivery:'35–45 min',image:'/images/hero.png',accent:'Pizza',description:'Loaded crusts, cheesy slices and oven-fresh sides.',items:[item('d1','Mozzarella Stuffed Crust',2200,'Large pizza with a cheese-filled crust'),item('d2','Creamy Tikka',650,'Creamy sauce, tikka chicken and mozzarella'),item('d3','Pizza Roll + Dip',550,'Hand-rolled pizza snack with dip')]},
{slug:'broadway-pizza',name:'Broadway Pizza',category:'Pizza',rating:4.6,delivery:'30–40 min',image:'/images/hero.png',accent:'Pizza',description:'Big, bold pizzas made for the whole table.',items:[item('br1','Celebration Deal',999,'Medium pizza, sides and chilled drink','Family pick'),item('br2','Dancing Fajita',1258,'Spiced chicken fajita with peppers'),item('br3','Garlic Bread',399,'Six golden pieces with garlic butter')]},
{slug:'kababjees',name:'Kababjees Fried Chicken',category:'Fried Chicken',rating:4.8,delivery:'25–35 min',image:'/images/chicken-biryani.jpg',accent:'Fried Chicken',description:'Crunchy comfort food and serious burgers.',items:[item('kj1','3 Stripzilla Deal',990,'Three crispy strips with fries'),item('kj2','Spicy Gigantic Burrito',650,'Loaded chicken burrito with fiery sauce'),item('kj3','Zenga Burger',600,'Crispy chicken burger with house sauce')]},
{slug:'milk-bar',name:'Milk Bar — Latifabad',category:'Drinks',rating:4.5,delivery:'15–25 min',image:'/images/hero.png',accent:'Drinks',description:'Thick shakes, milk sodas and cool treats.',items:[item('m1','Kitkat Chocolate Shake',405,'Chocolate shake blended with Kitkat'),item('m2','Oreo Chocolate Shake',430,'Creamy cookie shake'),item('m3','Pakola Milk Soda',216,'A nostalgic green milk soda')]},
{slug:'al-fajr',name:'Al Fajr Foods',category:'Pakistani',rating:4.4,delivery:'25–35 min',image:'/images/beef-biryani.jpg',accent:'Pakistani',description:'Everyday Pakistani favourites with generous portions.',items:[item('af1','Chicken Biryani',585,'Spiced chicken with basmati rice'),item('af2','Beef Biryani',580,'Tender beef layered with rice'),item('af3','Steak',799,'Grilled steak with house seasoning')]},
{slug:'bismillah-hotel',name:'Bismillah Hotel',category:'Pakistani',rating:4.3,delivery:'20–30 min',image:'/images/chicken-biryani.jpg',accent:'Pakistani',description:'Home-style curries, daal and fresh breads.',items:[item('bi1','Chicken Karahi',1105,'Chicken in rich tomato gravy','House special'),item('bi2','Daal Mash Fry',119,'Urad lentils with fried spices'),item('bi3','Tandoori Roti',21,'Whole wheat flatbread')]},
{slug:'california',name:'California Pizza',category:'Pizza',rating:4.5,delivery:'30–40 min',image:'/images/hero.png',accent:'Pizza',description:'Californian twists on classic pizza night.',items:[item('ca1','Chicken Supreme',300,'Chicken, peppers, onion and mushrooms'),item('ca2','Cheese Lover',300,'Extra mozzarella for the cheese devotee'),item('ca3','Arabian Malai Boti',330,'Malai chicken, garlic mayo and cheese')]},
{slug:'dream-pizza',name:'Dream Pizza',category:'Pizza',rating:4.4,delivery:'30–40 min',image:'/images/hero.png',accent:'Pizza',description:'Dreamy deals and comfort-food favourites.',items:[item('dr1','Dream Deal 4',1250,'Pizza, sides and drink for sharing'),item('dr2','Lava Pizza',764,'Cheesy pizza with a molten centre'),item('dr3','Chicken Sticks',382,'Crispy chicken sticks')]},
{slug:'greeno',name:'Greeno — Hyderabad',category:'Drinks',rating:4.6,delivery:'15–25 min',image:'/images/hero.png',accent:'Drinks',description:'Fresh juices, frappes and coffee for bright days.',items:[item('gr1','Falsa Juice',500,'Tart, refreshing seasonal juice'),item('gr2','Mango Milkshake',550,'Thick mango shake'),item('gr3','Hazelnut Frappe',808,'Iced coffee with hazelnut')]},
{slug:'king-shawarma',name:'The King Shawarma',category:'Fast Food',rating:4.5,delivery:'20–30 min',image:'/images/chicken-biryani.jpg',accent:'Fast Food',description:'Rolls, sandwiches and crispy broast plates.',items:[item('ks1','Club Sandwich',357,'Layered sandwich with fresh fillings'),item('ks2','Club Cheese Sandwich',357,'Classic club with melted cheese'),item('ks3','Super Broast',433,'Crispy single-serving broast')]},
{slug:'night-beef',name:'Night Beef Loader Biryani',category:'Biryani',rating:4.2,delivery:'20–30 min',image:'/images/beef-biryani.jpg',accent:'Biryani',description:'Late-night biryani, chapli kabab and chilled drinks.',items:[item('nb1','Beef Biryani',300,'Midnight comfort in a fragrant bowl'),item('nb2','Chapli Kabab',130,'Spiced beef kabab'),item('nb3','Midnight Deal 1',330,'Biryani, raita and a drink','Late night')]},
{slug:'sabir-tikka',name:'Sabir Tikka',category:'BBQ',rating:4.6,delivery:'25–35 min',image:'/images/beef-biryani.jpg',accent:'BBQ',description:'Charcoal-grilled plates and Pakistani street classics.',items:[item('st1','Beef Seekh Kabab Plate',810,'Smoky seekh kababs with sides'),item('st2','Beef Bihari Boti',799,'Tender marinated beef boti'),item('st3','Paratha',60,'Flaky layered flatbread')]},
{slug:'ravi-haleem',name:'Ravi Haleem',category:'Pakistani',rating:4.5,delivery:'25–35 min',image:'/images/beef-biryani.jpg',accent:'Pakistani',description:'Slow-cooked haleem and comforting Lahori favourites.',items:[item('rh1','Special Beef Haleem',420,'Slow-cooked wheat, lentils and tender beef','Signature'),item('rh2','Chicken Haleem',360,'Silky haleem with shredded chicken'),item('rh3','Naan',70,'Fresh tandoor-baked naan')]},
{slug:'burgers-broast',name:'Burgers & Broast',category:'Fast Food',rating:4.3,delivery:'25–35 min',image:'/images/chicken-biryani.jpg',accent:'Fast Food',description:'Simple burgers, broast and pan pizzas.',items:[item('bb1','Super Broast',433,'Crispy single-serving chicken'),item('bb2','Large Pizza',1100,'Loaded large pan pizza'),item('bb3','Small Pizza',500,'Classic small pan pizza')]}
];
export const categories=['All','Biryani','Pizza','Fried Chicken','Pakistani','Fast Food','Drinks','BBQ'];
export const getRestaurant=(slug:string)=>restaurants.find(r=>r.slug===slug);
