'use client'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useState } from 'react'
import { useCart, useOrders } from '@/components/providers'
import { SiteHeader } from '@/components/site-header'
export default function CheckoutPage() { const { lines, total } = useCart(); const { placeOrder } = useOrders(); const router = useRouter(); const [busy, setBusy] = useState(false); const [form, setForm] = useState({ name: '', email: '', address: '' })
 const submit = (event: React.FormEvent) => { event.preventDefault(); if (!lines.length) return router.push('/restaurants'); setBusy(true); setTimeout(() => { const order = placeOrder(form); if (order) router.push(`/success?order=${order.id}`) }, 700) }
 return <><SiteHeader /><main className="shell checkout-layout"><section><Link href="/cart" className="back-link">← Back to cart</Link><span className="eyebrow">Almost there</span><h1>Bring it home.</h1><p className="lede">A few details for the rider. No payment is collected in this portfolio demo.</p><form className="checkout-form" onSubmit={submit}><label>Full name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Your name" /></label><label>Email address<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" /></label><label>Delivery address<textarea required value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} placeholder="Street, area, Hyderabad" /></label><button className="primary-button" disabled={busy}>{busy ? 'Placing your order…' : 'Place mock order'}</button></form></section><aside className="order-summary"><span className="eyebrow">Your order</span><h2>{lines[0]?.restaurant.name || 'Your cart is empty'}</h2>{lines.map(line => <div className="summary-line" key={line.id}><span>{line.quantity} × {line.name}</span><strong>Rs. {(line.price * line.quantity).toLocaleString()}</strong></div>)}<div className="summary-total"><span>Total</span><strong>Rs. {total.toLocaleString()}</strong></div></aside></main></> }
